# this will hold the username and password for MongoDB application
# In this case, we use the secret for envronment variables, but it can have many
# more uses.
# See: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
# "Opaque" is the generic secret type of k8s
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
